### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Adblu** [cz172638/v4l-utils#7]
Hi. 

I want to set manual focus value for my camera but I'm getting error:

`(base) n@n:~$ sudo v4l2-ctl --device=6 --set-ctrl=focus_absolute=255 --log-status
VIDIOC_S_EXT_CTRLS: failed: Permission denied
Error setting controls: Permission denied
VIDIOC_LOG_STATUS: failed: Inappropriate ioctl for device
`

Coud anyone help ?

**Comment by cz172638** [comment]
this is question for upstream developers :) this is fork

**Comment by cz172638** [comment]
https://linuxtv.org/hg/dvb-apps

**Comment by cz172638** [comment]
https://www.linuxtv.org/wiki/index.php/LinuxTV_dvb-apps

**Comment by Adblu** [comment]
Sorry I'm not quite getting. 
Could you point me to some solution ?

**Comment by cz172638** [comment]
from help:
`--set-ctrl <ctrl>=<val>`
so
`v4l2-ctl --device=6 --set-ctrl focus_absolute=255 --log-status` instead of `v4l2-ctl --device=6 --set-ctrl=focus_absolute=255 --log-status`

**Comment by Adblu** [comment]
Problem solved but.... I was setting up everything correctly. 
What I had to do first, is disable focus_automatic_continous:
`sudo v4l2-ctl -d /dev/video0 -c focus_automatic_continuous=0`
after that command:
`v4l2-ctl -d /dev/video0 -c focus_absolute=1`
worked liked charm.

Thanks !
